### ISSUE TITLE
how to replace  opencv image prosess function cv::multiply()?

### ISSUE THREAD

**Issue by Royzon** [ermig1979/Simd#117]
Thanks very much for this wonderful works. I found the opencv funcion cv::multiply() is too slow to use in my work, but I can not find the substitute in this project.

**Comment by ermig1979** [comment]
cv::multiply performs per-element scaled product of two arrays. This operation is restricted memory bandwidth (algorithm performs only two multiplication for every element). So its performance achieves only several percents of maximum. And it practically does not depend of algorithm implementation. 
If you want to achiev good performance you have to use general matrix multiplication instead of per-element matrix multiplication.

**Comment by Royzon** [comment]
thanks for your reply.
