### ISSUE TITLE
VS2012 build fails

### ISSUE THREAD

**Issue by splisp** [ermig1979/Simd#124]
I am trying to build using VS2012 and I find this error:

v:\projects\simd.4.6.88\simd\src\simd\simdsynetconvolution8i.h(157): error C2039: 'fmax' : is not a member of '`global namespace''

Actually, VS2012's math.h doesn't have fmax()... Any suggestion?
Thanks!

**Comment by ermig1979** [comment]
Hello!
Thank you for bug report.

Really there are compiler errors for Visual Studio 2012 and Visual Studio 2013. The last are fixable and I have fixed them already. The bug fixing for Visual Studio 2012 is to hard  because there are too many places which use features of C++ 2011 standard. This is my fault. I check compatibility with Visual Studio 2012 too rarely. 

Are you really need to  Simd supports compatibility with Visual Studio 2012? The easiest way is stop the support.

**Comment by splisp** [comment]
> Are you really need to Simd supports compatibility with Visual Studio 2012? The easiest way is stop the support.

@ermig1979 thanks, I agree with you... I still have to support VS2012 but it's getting harder each month! I think you better drop VS2012 projects from simd, if the code can't compile there. On my side it will be just one more reason to do the same ;)
