### ISSUE TITLE
more like a suggestion rather than an issue

### ISSUE THREAD

**Issue by chibai** [ermig1979/Simd#14]
opencv just upload a new lbp face detection models in the early 2017
https://github.com/opencv/opencv/blob/master/data/lbpcascades/lbpcascade_frontalface_improved.xml
According to their paper, they (alomost) solved the false positve problem
you can add this model to your project

**Comment by ermig1979** [comment]
I've just checked this cascade. It has too low level of true positive detections. But of course also It has low level of false positive detections. But I think that missed objects are more important than false detections. Because in the second case we can use additional algorithms in order to filter false detections.
