### ISSUE TITLE
simd::nural

### ISSUE THREAD

**Issue by srikanthreddybethi** [ermig1979/Simd#19]
Hi @ermig1979,

I am using LBP face detection in arm based environment and its speed is awesome :).

do you have any example code for hog feature extraction for face detection/recognition and examples for neural module?

**Comment by ermig1979** [comment]
Hello.

Existed functions in Simd Library are used for optimization of HOG detection in dlib.  There is difficult to give a short example how they can be used. Because in order to do it I will need to reproduce  significant part of dlib. I hope that in future I will find free time to do it.

Relatively to Simd::Neural you can use NeuralTrainSpecialTest() in [TestNeural.cpp](https://github.com/ermig1979/Simd/blob/master/src/Test/TestNeural.cpp) as an using example.

**Comment by srikanthreddybethi** [comment]
thanks @ermig1979 !!!!

**Comment by srikanthreddybethi** [comment]
@ermig1979  thanks for your response!!!

I would be very interested in SimdMotion.hpp  for tracking... may I know which tracking algorithm you are using for it?   and do you think its ready. to be used?

**Comment by ermig1979** [comment]
Motion Detector is not ready yet. I can't find enough time and motivation to do it. But I will try :) .

P.S. Motion Detector is based on the background subtraction algorithm.

**Comment by srikanthreddybethi** [comment]
thanks for the info :)
